apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: beakerx-operator
rules:
- apiGroups:
  - ""
  - apps.openshift.io
  - route.openshift.io
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - deploymentconfigs
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - beakerx-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - beakerx.twosigma.com
  resources:
  - '*'
  verbs:
  - '*'
